Backport subdomain validation
zendesk/zendesk_api_client_php pull request #477
Opened 2021-11-16 01:17 UTC by sanmai

This PR backports subdomain validation from #466, necessary to fix CVE-2021-30492.

I also added/fixed tests. Here's how you can run them: 
```
php vendor/bin/phpunit tests/Zendesk/API/UnitTests/InvalidSubdomainTest.php
php vendor/bin/phpunit tests/Zendesk/API/UnitTests/OrganizationsTest.php
```

All should be left is to tag a new release and update the Packagist registry.

2024-02-25 23:03 UTC, ecoologic requested changes
Thank you very much for your contribution. ❤️ 

Please note the required changes.

2024-02-25 23:03 UTC, ecoologic commented on tests/Zendesk/API/UnitTests/OrganizationsTest.php
>  <?php
This file does not exist in current master, and a similar issue has already been fixed, can you please try to merge master in here?

2024-02-25 23:03 UTC, ecoologic commented on tests/Zendesk/API/UnitTests/InvalidSubdomainTest.php
> +    }
I'm afraid we would need a more specific test.

2024-02-26 11:21 UTC, sanmai commented on tests/Zendesk/API/UnitTests/InvalidSubdomainTest.php
> +    }
I'm happy to add one. What test would you like to see?

2024-02-26 13:31 UTC, sanmai commented
Alternatively, I'll be happy to close this PR as it looks like it is no longer necessary for my cause.

2024-05-27 00:51 UTC, ecoologic reviewed
Hi @sanmai  - thank you very much for your contribution and patience.

I know we've not given a reasonable feedback loop in the past, but moving forward, we are committed to maintaining this library and be nicer to our awesome open-source contributors.

Please keep in mind though, that I personally don't have a deep knowledge of this lib nor PHP, but I'll do my best in a world of conflicting priorities.

With that said, would you be so kind to address the comments?

Thanks a lot, long live open-source ❤️

2024-05-27 00:51 UTC, ecoologic commented on tests/Zendesk/API/UnitTests/GroupMembershipsTest.php
> +namespace Zendesk\API\UnitTests;
Thank you ❤️

2024-05-27 00:51 UTC, ecoologic commented on tests/Zendesk/API/UnitTests/InvalidSubdomainTest.php
> +    }
You're introducing a regex, could you please provide a test that passes the validation and one that throws `InvalidArgumentException`?

2024-05-29 05:42 UTC, sanmai commented on tests/Zendesk/API/UnitTests/InvalidSubdomainTest.php
> +    }
Done!

2024-05-29 21:30 UTC, ecoologic approved these changes
Thank you for your contribution @sanmai.

We only maintain the latest version, but surely we welcome improving the value or older versions.

2024-05-29 21:30 UTC, ecoologic commented on tests/Zendesk/API/UnitTests/OrganizationsTest.php
>  <?php
Thank you for the clarification.

2024-05-29 21:31 UTC, merged